#!/usr/bin/env bash
# We stopped our 4-to_infinity_and_beyond process using ctrl+c
# in the previous task, there is actually another way to do this
pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$pid" ];
then
    kill "$pid"
fi
