#!/usr/bin/env bash
# The file /etc/passwd has already been covered in a previous
# project and you should be familiar with it. Today we will make up a story based on it.

while IFS=":" read -r username password user_id group_id info home_dir command_shell;
do
    echo "The user ${username} is part of the ${group_id} gang, lives in ${home_dir} and rides ${command_shell}. ${user_id}'s place is protected by the passcode ${password}, more info about the user here: ${info}"
done < "/etc/passwd"
